# development container for pyconsul
FROM python:3.4

# TODO pin deps
# install app dependencies
RUN pip install \
  requests==2.7.0
# install dev dependencies
RUN pip install \
  nose==1.3.7 \
  yanc==0.3.3 \
  pep8==1.6.2 \
  coveralls==0.5 \
  piprot==0.9.1 \
  responses==0.4.0

# dev tools
RUN pip install httpie ipython mkdocs

# mkdocs server
EXPOSE 8000
